- README.md
- packages/cli/README.md
- packages/fastman/README.md
- packages/fetch/README.md
- packages/mongoose-helper/README.md
- packages/query-normalizr/README.md
- packages/swagen/README.md
- packages/tpl-cli/README.md
- packages/tpl-module/README.md
- packages/tpl-react/README.md
- packages/tpl-service/README.md
- packages/tpl-tcp/README.md
[query-normalizr](https://www.npmjs.com/package/@36node/query-normalizr) has not been published.
> chore: doc add badge

- packages/fastman/package.json
- packages/fastman/src/cli/fastman-export.js
- packages/fastman/src/cli/fastman-import.js
- packages/fastman/src/cli/fastman-ls.js
- packages/fastman/src/helpers.js
- yarn.lock
> feat: fastman add prompt if api key not config

- packages/cli/bin/sketch-build.js
- packages/cli/bin/sketch-init.js
- packages/tpl-react-component/.circleci/config.yml
- packages/tpl-react-component/.storybook/addons.js
- packages/tpl-react-component/.storybook/config.js
- packages/tpl-react-component/.storybook/webpack.config.js
- packages/tpl-react-component/README.md
- packages/tpl-react-component/package.json
- packages/tpl-react-component/src/__snapshots__/index.test.js.snap
- packages/tpl-react-component/src/index.js
- packages/tpl-react-component/src/index.test.js
- packages/tpl-react-component/stories/index.js
- yarn.lock
Issue(#61 )
添加 tpl-react-component,
> feat: tpl react-component 

- package.json
- packages/tpl-cra-redux/package.json
- packages/tpl-cra-redux/src/app.js
Issue(#66 )
* tpl-cra-loadable 模版添加 react loadable
> feat: add react loadable

- packages/tpl-cra-redux/src/app.js
- packages/tpl-cra-redux/src/components/loading/index.js
- yarn.lock
Issue(#66 )
* 加入 Loading 组件
* 更新 yarn.lock
> fix: fix tpl-cra-redux, add loading

- packages/cli/config-overrides.js
- packages/tpl-cra-redux/src/actions/index.js
- packages/tpl-cra-redux/src/app.js
- packages/tpl-cra-redux/src/containers/github.js
- packages/tpl-cra-redux/src/containers/home.js
- packages/tpl-cra-redux/src/containers/login.js
- packages/tpl-cra-redux/src/containers/pet-store.js
- packages/tpl-cra-redux/src/containers/protect.js
- packages/tpl-cra-redux/src/reducers/index.js
- packages/tpl-cra-redux/src/sagas/api.js
Issue(#72 )
* 增加以下 alias:
* src
* actions
* components
* containers
* reducers
* sagas
* sdk
* selectors
* 更新 tpl-cra-redux 的模块引用
> feat: add webpack resolve

- packages/query-normalizr/README.md
- packages/query-normalizr/src/lib/denormalize.js
- packages/query-normalizr/src/lib/denormalize.test.js
- packages/query-normalizr/src/lib/normalize.js
- packages/query-normalizr/src/lib/normalize.test.js
Issue(#81 )
在query-normalizr 中 对 _like 条件支持数组
> feat: qn support _like array

- packages/tpl-cra-redux/README.md
- packages/tpl-cra-redux/public/index.html
- packages/tpl-cra-redux/src/config.js
- packages/tpl-cra-redux/src/sagas/api.js
#75 
模仿shanghaibus-web，变量注入index.html的实现在
https://github.com/zzswang/docker-nginx-react/pull/15
> feat: add runtime env config (#75)

- packages/eslint-config/index.js
- packages/fetch/package.json
- packages/fetch/src/browser.js
- packages/fetch/src/wrapper.js
- packages/fetch/src/wxapp-fetch.js
- yarn.lock
Issue(#85 )
* eslint-config 将 `wx` 作为全局变量
* `wxapp-fetch.js` 代码来自 [axetroy/wxapp-fetch](https://github.com/axetroy/wxapp-fetch/blob/master/index.js)，并且修复了 headers 的 `get` 和 `has` 方法，新加 forEach 方法
*  `browser.js` 中通过全局变量 window 和 wx 判断是否是微信小程序的环境
> feat: support fetch in wxapp

- packages/query-normalizr/src/lib/denormalize.js
- packages/query-normalizr/src/lib/normalize.js
- packages/query-normalizr/src/lib/to-json-server.js
Issue(#92  )
* 按文件的方式引用 lodash 方法，在微信小程序中不会报错
> fix: make query-normalizr support wxapp

- packages/cli/config-overrides.js
- packages/tpl-cra-redux/src/app.js
- packages/tpl-cra-redux/src/containers/github.js
- packages/tpl-cra-redux/src/containers/home.js
- packages/tpl-cra-redux/src/containers/login.js
- packages/tpl-cra-redux/src/containers/pet-store.js
- packages/tpl-cra-redux/src/containers/redux-ui.js
Issue(#90 )
* 去除 webpack resolve 配置
> fix: remove webapck resolve

- packages/koa-health/package.json
- packages/koa-openapi/package.json
- packages/tpl-service/test/jest.setup.js
- packages/tpl-service/test/jest.teardown.js
- packages/tpl-tcp/package.json
- packages/tpl-tcp/test/jest.config.js
- packages/tpl-tcp/test/jest.setup.js
- packages/tpl-tcp/test/jest.teardown.js
- packages/tpl-tcp/test/protocol.test.js
Issue(#96 )
* 集成测试加 `globalSetup` 和 `globalTeardown`
> feat: add setup and teardown to test config

- packages/redux-api/CHANGELOG.md
- packages/redux-api/package.json
- packages/redux-form/CHANGELOG.md
- packages/redux-form/package.json
- packages/redux-xlsx/CHANGELOG.md
- packages/redux-xlsx/package.json
- packages/tpl-cra-redux/CHANGELOG.md
- packages/tpl-cra-redux/package.json
- @36node/redux-api@0.1.11
- @36node/redux-form@0.0.2
- @36node/redux-xlsx@0.0.1
- @36node/template-cra-redux@0.10.20
发布 redux-xlsx
> chore(release): publish

- packages/redux-xlsx/typings/index.d.ts
改掉了一个拼写错误，影响自动补全，不用立即发布，等晚上自动发包即可
> fix: redux-xlsx index.d.ts spelling mistake

- packages/redux-xlsx/src/action.js
- packages/redux-xlsx/src/index.js
- packages/redux-xlsx/src/reducer.js
- packages/redux-xlsx/src/saga.js
- packages/redux-xlsx/typings/index.d.ts
- packages/tpl-cra-redux/src/actions/pets-xlsx.js
> refactor: adjust xlsx actions

- packages/cli/package.json
- yarn.lock
> fix: upgrade esm version

- packages/cli/bin/sketch-test.js
> feat: add runInBand option for sketch test (#123)

- README.md
- packages/browserslist-config/README.md
- packages/cli/README.md
- packages/eslint-config/README.md
- packages/mock-server/README.md
- packages/redux-api/README.md
- packages/redux-cron/README.md
- packages/redux-form-antd/README.md
- packages/redux-form/README.md
- packages/redux-ui/README.md
- packages/redux-xlsx/README.md
- packages/tpl-cra-redux/README.md
- packages/tpl-react-component/README.md
> docs: update readme

- packages/tpl-cra-redux/Dockerfile
- packages/tpl-cra-redux/public/index.html
https://github.com/zzswang/bus-admin/issues/76
> fix: use runtime env

- packages/redux-antd/src/table.js
Issue(#157 )
修改redux-antd-table
> fix: redux antd table(#157)

- packages/tpl-cra-redux/src/components/withTable/exporter.js
- packages/tpl-cra-redux/src/components/withTable/importer.js
- packages/tpl-cra-redux/src/components/withTable/index.js
- packages/tpl-cra-redux/src/containers/store/index.js
> feat: withTable

- packages/redux-xlsx/src/lib.js
- packages/tpl-cra-redux/src/containers/store/index.js
当多层时，按children.length计算col偏移不准确
> fix: export

- packages/tpl-cra-redux/src/containers/store/index.js
> fix: pet stroe import

- packages/redux-xlsx/src/saga.js
> fix: xlsx-import date

- packages/redux/src/lib/action.js
- packages/redux/src/toggle/reducer.test.js
Issue(#167 )
修复redux toggle bug
增加toggle reducer的单元测试
> fix: toggle do not overturn (#167)

- packages/redux/src/lib/store.js
- packages/redux/typings/index.d.ts
Issue(#170 )
1. redux增加中间件配置
2. 经过讨论，redux-session 暂时不做修改
> chore: redux support middleware

- packages/fastman/bin/fastman-export.js
- packages/fastman/bin/fastman-ls.js
- packages/fastman/bin/fastman.js
- packages/fastman/src/postman-api.js
Issue(#175 )
1. ls的时候显示uid
2. 删除的时候传入uid
3. export uid filepath
更新help：
```
Usage: fastman [options] [command]
Options:
-V, --version            output the version number
-h, --help               output usage information
Commands:
config                   config fastman, like postman api key eg..
ls                       list collections exist in postman
delete [uid]             delete a collection by uid
import [file]            import a collection file to postman
export [uid] [filepath]  export collection file with name, saved in filepath(default is ./postman_collection.json)
help [cmd]               display help for [cmd]
```
ls: 
```
571979-394d5ec6-9b96-4c33-9cac-20a4e0cb0f88 bus-core-vehicle-curd
571979-396a07b6-3b2e-4120-b934-6e9b6508ab24 Postman …
```
> feat(fastman): ls show uid & delete by uid

- packages/redux-antd/src/table.js
- packages/swagen/src/generators/sdk.js
- packages/swagen/src/index.js
- packages/swagen/templates/sdk/definitions.hbs
- packages/swagen/templates/sdk/sdk.hbs
- packages/tpl-cra-redux/src/components/withTable/index.js
- packages/tpl-cra-redux/src/containers/store/index.js
- packages/tpl-sdk/src/index.js
- packages/tpl-sdk/typings/index.d.ts
> chore: swaggen support new sdk tpl
